### ISSUE TITLE
Crash when 200 or more lines

### ISSUE THREAD

**Issue by chapmanjacobd** [mfs-git/watchall#5]
```
Exception in thread Thread-1:
  Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner  self.run()
                                                                                                                                                        File "/usr/lib64/python3.8/threading.py", line 870, in run
                 self._target(*self._args, **self._kwargs)
 File "/home/xk/.local/bin/watchall", line 85, in update_lines  self.refresh_screen(update_pad=True)
                                                                                                                                                                   File "/home/xk/.local/bin/watchall", line 120, in refresh_screen
       self.pad.addch(self.cur_output_lines[i][j])     _curses.error: add_wch() returned ERR

```

**Comment by wallart1** [comment]
Have you seen the -m option? I use it to set the maximum number of output lines.
